db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  volumes_from:
    - bundler-cache
  ports:
    - "3000:3000"
  links:
    - db
bundler-cache:
  image: ruby:2.2
  command: /bin/true
  volumes:
    - /usr/local/bundle
