# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae4c56ad9eec89764e742be84f7ff0d4d66571b13a3e928d0929cee9c41ce339625d5c2aba91ecf9333b1d65e1f832b5185a3538530c942fd2f658eeb81f6ae7

test:
  secret_key_base: 498cdf44562116493d1f1b3c0ce61eaf0762034eb4aaf482aba2e94bb94a8df1e1f2bac0fcbf4a6f71edea7eb1887d33b2007ea1c8b6699edea2d6686b3bab97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
